#!/bin/bash


## YOU HAVE TO ADD fPIC to CFLAGS and FFLAGS in the fortran main makefile other
# this obviously wont work!
BASEDIR=~/Projects/mastercode/
cd $BASEDIR/FeynHiggs-2.5.1/build/
gfortran cache.o ini.o auxB.o auxCD.o A0.o B0.o B1.o B00.o B11.o DB0.o DB1.o DB00.o DB11.o C0.o Cget.o myA0del.o myG.o Gauss.o EigenSf.o HEigensystem.o SEigensystem.o TakagiFactor.o SVD.o ReverseEigen.o ReverseTakagi.o ReverseSVD.o Pair.o VecSet.o Eps.o SLHAClear.o SLHARead.o SLHAWrite.o SLHAInfo.o SLHANewDecay.o SLHAFindDecay.o SLHAAddDecay.o SLHAGetDecay.o SLHADecayTable.o SLHAValid.o SLHAExist.o SLHAPDGName.o SLHACopyString.o TLCorr.o TLasat.o TLasab.o TLatab.o TLatat.o Pi11t.o Pi12t.o Pi22t.o Pi11b.o Pi12b.o Pi22b.o Pitt.o InvTri.o Dilog.o Li2.o Phi.o TF.o SetFlags.o SetPara.o SetSLHA.o SetCKM.o SetNMFV.o Para.o SetDebug.o GetPara.o GetSelf.o HiggsCorr.o Uncertainties.o Couplings.o SelectUZ.o Constraints.o HiggsProd.o DeltaMB.o CalcSelf.o Error.o DRbartoOS.o AlfasMH.o AlphaS.o  se_h0h0.o se_HHHH.o se_A0A0.o se_HmHp.o se_h0HH.o se_h0A0.o se_HHA0.o se_G0G0.o se_h0G0.o se_HHG0.o se_A0G0.o se_GmGp.o se_HmGp.o se_A0Z.o se_ZZ.o se_WW.o td_h0.o td_HH.o td_A0.o dse_h0h0.o dse_HHHH.o dse_A0A0.o dse_HmHp.o dse_h0HH.o dse_h0A0.o dse_HHA0.o dse_G0G0.o dse_h0G0.o dse_HHG0.o dse_A0G0.o dse_GmGp.o dse_HmGp.o dse_ZZ.o dse_WW.o  hgaga.o hgaga-squaredme.o hgaga-abbr_s.o hgaga-abbr_hel.o hgaga-vert.o hgaga-vert_Cha1.o hgaga-vert_Gen1.o hgaga-vert_Gen1_Sfe1.o hgaga-vert_All1_Ind1_Ind2.o hgagaSM.o hgagaSM-squaredme.o hgagaSM-abbr_s.o hgagaSM-abbr_hel.o hgagaSM-vert.o hgagaSM-vert_Gen1.o hgg.o hgg-squaredme.o hgg-abbr_s.o hgg-abbr_hel.o hgg-vert_Gen1.o hgg-vert_All1_Ind1_Ind2.o hggSM.o hggSM-squaredme.o hggSM-abbr_s.o hggSM-abbr_hel.o hggSM-vert_Gen1.o hhh.o hhh-squaredme.o hhh-abbr_s.o hhh-vert_All1_All2_Ind1_Ind2_Ind3.o gm2_1L.o gm2_2L_short1.o gm2_2L_short2.o EWPO.o DeltaRho_1L.o DeltaRho_2L.o EDM.o Bsgamma.o -lpthread -L/lib/ld-linux-x86-64.so.2 -L/usr/lib/gcc/x86_64-unknown-linux-gnu/4.6.2 -L/usr/lib/gcc/x86_64-unknown-linux-gnu/4.6.2/../../../../lib -L/lib/../lib -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-unknown-linux-gnu/4.6.2/../../.. -lgfortran -lm -lgcc_s -lgcc -lquadmath -lm -lgcc_s -lgcc -lc -lgcc_s -lgcc -ffree-form -shared -o $BASEDIR/py_masterfitter/libs/libFH.so
cd $BASEDIR
