version=5.34.04
name=root_v$(version)
#src_dir=$(UTIL_DIR)/root
#lib_dir=$(LIB_DIR)
#lib=$(INSTALL_DIR)/lib/libPyROOT.so
#tar_name=$(name).source.tar.gz
#remote=ftp://root.cern.ch/root/$(tar_name)
#tarfile=$(TAR_DIR)/$(tar_name)
interface_src=$(STORAGE_DIR)/interfaces/ROOT.cc
interface_lib=$(LIB_DIR)/libmcROOT.so
#interface_read_src=$(STORAGE_DIR)/interfaces/ROOT_read.cc
#interface_read_lib=$(LIB_DIR)/libmcROOT_read.so
#interface_ab_out_src=$(STORAGE_DIR)/interfaces/ROOT_ab_out.cc
#interface_ab_out_lib=$(LIB_DIR)/libmcROOT_ab_out.so
root_flags=$(shell root-config --cflags --libs )
#python_incdir=$(shell python -c  "import distutils.sysconfig as du; print(du.get_python_inc())" )
#python_libdir=$(shell python -c "import sys; print( sys.prefix )")/lib

cc=g++
