/********************************************************************
* output.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error output.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableoutput();
extern void G__cpp_setup_inheritanceoutput();
extern void G__cpp_setup_typetableoutput();
extern void G__cpp_setup_memvaroutput();
extern void G__cpp_setup_globaloutput();
extern void G__cpp_setup_memfuncoutput();
extern void G__cpp_setup_funcoutput();
extern void G__set_cpp_environmentoutput();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../inc/SLHAblock.hh"
#include "../inc/SLHAfile.hh"
#include "../inc/SLHAline.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__outputLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__outputLN_string;
extern G__linked_taginfo G__outputLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__outputLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__outputLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__outputLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__outputLN_SLHAline;
extern G__linked_taginfo G__outputLN_SLHAblock;
extern G__linked_taginfo G__outputLN_pairlEunsignedsPintcOunsignedsPintgR;
extern G__linked_taginfo G__outputLN_vectorlESLHAlinecOallocatorlESLHAlinegRsPgR;
extern G__linked_taginfo G__outputLN_reverse_iteratorlEvectorlESLHAlinecOallocatorlESLHAlinegRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__outputLN_SLHAfile;
extern G__linked_taginfo G__outputLN_vectorlESLHAblockcOallocatorlESLHAblockgRsPgR;
extern G__linked_taginfo G__outputLN_reverse_iteratorlEvectorlESLHAblockcOallocatorlESLHAblockgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
